apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: teste
  labels:
    app: demo
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: demo
  type: LoadBalancer